version: '3.8'
services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/google_credentials.json:/app/google_credentials.json # Montar el archivo de credenciales

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
